const Groq = require("groq-sdk")
const puppeteer = require("puppeteer")

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY
})

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {
  const prompt = `You are an expert interview coach. Generate an interview report as a JSON object.

Job Description: ${jobDescription}
Resume: ${resume || "Not provided"}
Self Description: ${selfDescription || "Not provided"}

Return ONLY a JSON object with exactly these fields:
{
  "title": "job title string",
  "matchScore": number between 0-100,
  "technicalQuestions": [
    {
      "question": "question string",
      "intention": "intention string",
      "answer": "answer string"
    }
  ],
  "behavioralQuestions": [
    {
      "question": "question string",
      "intention": "intention string",
      "answer": "answer string"
    }
  ],
  "skillGaps": [
    {
      "skill": "skill string",
      "severity": "low" or "medium" or "high"
    }
  ],
  "preparationPlan": [
    {
      "day": 1,
      "focus": "focus string",
      "tasks": ["task1", "task2"]
    }
  ]
}

Generate at least 5 technical questions, 5 behavioral questions, 3 skill gaps and a 7 day preparation plan.
Return ONLY the JSON object, no extra text.`

  const response = await groq.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: [
      {
        role: "user",
        content: prompt
      }
    ],
    response_format: { type: "json_object" },
    temperature: 0.7,
  })

  return JSON.parse(response.choices[0].message.content)
}

async function generatePdfFromHtml(htmlContent) {
  const browser = await puppeteer.launch({
    args: ["--no-sandbox", "--disable-setuid-sandbox"]
  })
  const page = await browser.newPage()
  await page.setContent(htmlContent, { waitUntil: "networkidle0" })

  const pdfBuffer = await page.pdf({
    format: "A4",
    margin: {
      top: "20mm",
      bottom: "20mm",
      left: "15mm",
      right: "15mm"
    }
  })

  await browser.close()
  return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  const prompt = `You are an expert resume writer. Generate a professional resume in HTML format.

Job Description: ${jobDescription}
Resume: ${resume || "Not provided"}
Self Description: ${selfDescription || "Not provided"}

Return ONLY a JSON object with exactly this field:
{
  "html": "complete HTML content of the resume"
}

The resume should be:
- Tailored for the given job description
- Well formatted and visually appealing with simple professional styling
- ATS friendly
- Ideally 1-2 pages when converted to PDF
- Not sound like it is generated by AI

Return ONLY the JSON object, no extra text.`

  const response = await groq.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: [
      {
        role: "user",
        content: prompt
      }
    ],
    response_format: { type: "json_object" },
    temperature: 0.7,
  })

  const jsonContent = JSON.parse(response.choices[0].message.content)
  const pdfBuffer = await generatePdfFromHtml(jsonContent.html)
  return pdfBuffer
}

module.exports = { generateInterviewReport, generateResumePdf }