import React, { useEffect } from 'react';
import { Link } from 'react-router';
import '../style/legal.scss';

const Terms = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <>
      <main className="legal-page">
        <div className="glass-panel">
          <div className="legal-page__header">
            <h1>Terms of Service</h1>
            <p>Last updated: August 2026</p>
          </div>
          
          <div className="legal-page__content">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using this application, you accept and agree to be bound by the terms and provision of this agreement. 
              If you do not agree to abide by the above, please do not use this service.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              AI Interview provides a platform for users to practice mock interviews using generative AI technology. 
              The service includes voice-to-text transcription, AI-generated feedback, and performance scoring.
            </p>

            <h2>3. User Conduct</h2>
            <p>You agree to use the service only for lawful purposes. You are prohibited from:</p>
            <ul>
              <li>Using the service to transmit any unlawful, threatening, or abusive content.</li>
              <li>Attempting to interfere with, degrade, or disable the service (e.g., via DDoS or automated scraping).</li>
              <li>Impersonating another person or entity through our OAuth integration.</li>
            </ul>

            <h2>4. Disclaimer of Warranties</h2>
            <p>
              The AI feedback provided by this platform is generated by large language models (Google Gemini) and should be used 
              for educational and practice purposes only. We do not guarantee the accuracy, completeness, or usefulness of the 
              feedback. The service is provided on an "AS IS" and "AS AVAILABLE" basis.
            </p>

            <h2>5. Limitation of Liability</h2>
            <p>
              In no event shall AI Interview or its developers be liable for any direct, indirect, incidental, special, or 
              consequential damages resulting from the use or the inability to use the service.
            </p>
          </div>
          
          <div className="legal-page__back">
            <Link to="/">← Back to Home</Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Terms;
